DROP TABLE ROLE CASCADE CONSTRAINTS;
CREATE TABLE ROLE
  (
    ROLE_ID 		VARCHAR2 (2 BYTE) NOT NULL ,
    ROLE_NAME      	VARCHAR2 (40 BYTE) NOT NULL ,
	CREATED_BY      VARCHAR2 (80 BYTE) NOT NULL ,
	CREATED_TS      TIMESTAMP(6) ,
    UPDATED_TS      TIMESTAMP(6) ,
    UPDATED_BY      VARCHAR2 (80 BYTE) ,
    VERSION         NUMBER (10) DEFAULT 1 NOT NULL
  )
TABLESPACE user_01;
ALTER TABLE ROLE ADD CONSTRAINT PK_ROLE_ID PRIMARY KEY ( ROLE_ID ) USING INDEX TABLESPACE user_01  ENABLE;

DROP SEQUENCE ROLE_SEQ;
CREATE SEQUENCE ROLE_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER  T_ROLE_SEQ_BI 
BEFORE INSERT ON ROLE FOR EACH ROW
WHEN (NEW.ROLE_ID IS NULL) BEGIN
SELECT ROLE_SEQ.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
END;
/
ALTER TRIGGER T_ROLE_SEQ_BI ENABLE; 

ALTER TABLE ROLE MODIFY ROLE_ID NUMBER(10,0);