DROP TABLE USER_ROLE_MAPPING CASCADE CONSTRAINTS;
CREATE TABLE USER_ROLE_MAPPING
  (
    USER_ROLE_MAPPING_ID 	NUMBER(10,0) NOT NULL ,
    ROLE_ID      	NUMBER(10,0) NOT NULL REFERENCES ROLE(ROLE_ID),
	USER_ID      	NUMBER(10,0) NOT NULL REFERENCES USERS(USER_ID) ,
	CREATED_BY      VARCHAR2 (80 BYTE) NOT NULL ,
	CREATED_TS      TIMESTAMP(6) ,
    UPDATED_TS      TIMESTAMP(6) ,
    UPDATED_BY      VARCHAR2 (80 BYTE) ,
    VERSION         NUMBER (10) DEFAULT 1 NOT NULL
  )
TABLESPACE user_01;
ALTER TABLE USER_ROLE_MAPPING ADD CONSTRAINT PK_USER_ROLE_MAPPING_ID PRIMARY KEY ( USER_ROLE_MAPPING_ID ) USING INDEX TABLESPACE user_01  ENABLE;


DROP SEQUENCE USER_ROLE_MAPPING_SEQ;
CREATE SEQUENCE USER_ROLE_MAPPING_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER  T_USER_ROLE_MAPPING_SEQ_BI 
BEFORE INSERT ON USER_ROLE_MAPPING FOR EACH ROW
WHEN (NEW.USER_ROLE_MAPPING_ID IS NULL) BEGIN
SELECT USER_ROLE_MAPPING_SEQ.NEXTVAL INTO :NEW.USER_ROLE_MAPPING_ID FROM DUAL;
END;
/
ALTER TRIGGER T_USER_ROLE_MAPPING_SEQ_BI ENABLE; 
